### PR TITLE
Require TRAMP from ob-jupyter

### LINKED ISSUE #261: tramp-tramp-file-p function void
If I have a fresh session (no use of tramp yet) and try to use tab completion in an jupyter org block I get the following error:
```
  tramp-tramp-file-p("jj-symb_diag")
  jupyter-tramp-file-name-p("jj-symb_diag")
  (if (jupyter-tramp-file-name-p session) (progn (setq default-directory (concat (file-remote-p session) "/"))))
  (let* ((params (nth 2 info)) (session (alist-get :session params)) (client-buffer (org-babel-jupyter-initiate-session session params))) (jupyter-repl-associate-buffer client-buffer) (if (jupyter-tramp-file-name-p session) (progn (setq default-directory (concat (file-remote-p session) "/")))))
  org-babel-edit-prep:jupyter-julia(("jupyter-julia" "using LinearAlgebra\n\n\nusing SymPy\nimport Base.imag\nimport Base.real\nimag(x::Sym) = sympy.im(x)\nreal(x::Sym) = sympy.re(x)\nimport Base.adjoint\nadjoint(x::Sym) = conj(x)\n\nusing Plots\ntheme(:default)\npgfplotsx()\n\nusing TikzPictures\nfunction tikzvec(v)\n  l = length(v)\n  @assert 2 <= l <=3\n  if l == 2\n    return \"({$(v[1])}, {$(v[2])})\"\n  elseif l == 3\n    # we need the minus sign here to get the right handed rotations\n    return \"({$(v[1])}, {$(v[3])}, {$(-v[2])})\"\n  end\nend\n\nusing LaTeXStrings\nusing Latexify\nfunction latex(key)\n  temp = replace(\"$key\", r\"([CSσ])([\\dd])_(\\d)([mp]*)\" => s\"\\1_{\\2,\\3\\4}\")\n  temp = replace(temp, r\"([AET])([\\d])\" => s\"\\1_{\\2}\")\n  temp = replace(temp, \"p\"=>\"+\")\n  temp = replace(temp, \"m\"=>\"-\")\n  temp = replace(temp, \"σ\"=>\"\\\\sigma\")\n  temp = replace(temp, \"C3v\"=>\"C_{3v}\")\n  temp = replace(temp, \"Td\"=>\"T_d\")\n  \"\\\\( $temp \\\\)\"\nend\nlatex(key::Sym) = sympy.latex(key)\n\nusing Unitful\nusing PhysicalConstants: CODATA2018\nCD18 = CODATA2018\n\nval(x::Number) = x\nval(x::Quantity) = x.val\n\nfunction createJoperators(j)\n  length = convert(Int, 2*j+1)\n  ms = j:-1:-j\n  Jplus = [(ms[i1]-ms[i2])==1 ? sqrt(j*(j+1)-ms[i2]*(ms[i2]+1)) : convert(typeof(j), 0)\n       for i1 in 1:length, i2 in 1:length]\n  Jminus = [(ms[i2]-ms[i1])==1 ? sqrt(j*(j+1)-ms[i2]*(ms[i2]-1)) : convert(typeof(j), 0)\n       for i1 in 1:length, i2 in 1:length]\n  Jx = (Jplus .+ Jminus)./2\n  Jy = (Jplus .- Jminus)./(2im)\n  Jz = diagm([ms[i] for i in 1:length])\n  (Jx, Jy, Jz, Jplus, Jminus)\nend\n\n# sakurai p. 528\nfunction sphericalharmonics(l::Int,m::Int;\n              θ=symbols(\"theta\",positive=true),φ=symbols(\"varphi\",positive=true))\n  @assert l >= 0\n  @assert l >= abs(m)\n  if m < 0\n    return (-1)^(-m) * conj(sphericalharmonics(l,-m; θ=θ, φ=φ))\n  end\n  norm = (-1)^m * sqrt((2*l+1)/(4*PI) * factorial(l-m)/Sym(factorial(l+m)))\n  x=symbols(\"x\")\n  pl = (-1)^l/(Sym(2^l)*factorial(l))*diff((1-x^2)^(l), x, l)\n  plm = (1-cos(θ)^2)^(m/Sym(2)) * subs(diff(pl, x, m), x=>cos(θ))\n  norm * exp(1im*m*φ) * plm\nend\n\nfunction clebschgordancoefficient((p, s), (q, t), (r, u); α=1, kys=nothing)\n  kys = kys==nothing ? keys(q) : kys\n  if α==0\n    return Sym(0)\n  elseif α==1\n    g = length(kys)\n    d_q = convert(Int64, tr(q[:E]))\n    d_p = convert(Int64, tr(p[:E]))\n    d_r = convert(Int64, tr(r[:E]))\n    dnm = Sym(0)\n    for j in 1:d_p, k in 1:d_q, l in 1:d_r\n      dnm = expand(sum(p[key][j,j]*q[key][k,k]*conj(r[key][l,l]) for key in kys),\n             complex=true)\n      if dnm != 0\n        return expand(sqrt(Sym(d_r)/Sym(g))*\n               sum(p[key][s,j]*q[key][t,k]*conj(r[key][u,l]) for key in kys)/\n               dnm,\n               complex=true)\n      end\n    end\n    @assert dnm != 0\n  else\n    @error α>1\n  end\nend\n\nfunction normalizedcgc((p, s), (q, t), (r, u); α=1)\n  d_q = convert(Int64, tr(q[:E]))\n  d_p = convert(Int64, tr(p[:E]))\n  d_r = convert(Int64, tr(r[:E]))\n  temp = [clebschgordancoefficient((p, j), (q, k), (r, u); α=α)\n      for j in 1:d_p, k in 1:d_q]\n  simplify.(expand.(temp[s,t]/(nm = norm(reshape(temp[:,:], d_q*d_p));\n                 nm == 0 ? 1 : nm), complex=true))\nend\n\nrotatevector_x(φ) = [one(φ) zero(φ) zero(φ);\n           zero(φ) cos(φ) -sin(φ);\n           zero(φ) sin(φ) cos(φ)]\nrotatevector_y(φ) = [cos(φ) zero(φ) sin(φ);\n           zero(φ) one(φ) zero(φ);\n           -sin(φ) zero(φ) cos(φ)]\nrotatevector_z(φ) = [cos(φ) -sin(φ) zero(φ);\n           sin(φ) cos(φ) zero(φ);\n           zero(φ) zero(φ) one(φ)]" ((:results . "silent raw") (:exports . "both") (:session . "jj-symb_diag") (:eval . "no-export") (:async . "yes") (:kernel . "julia-1.4") (:tangle . "no") (:hlines . "no") (:noweb . "no") (:cache . "no")) "" nil 361 "(ref:%s)"))
  org-edit-src-code()
  (and (org-babel-where-is-src-block-head element) (org-edit-src-code))
  (if (and (org-babel-where-is-src-block-head element) (org-edit-src-code)) (progn (unwind-protect (progn (call-interactively (function indent-for-tab-command))) (org-edit-src-exit) (if outside-position (progn (goto-char outside-position)))) t))
  (let* ((element (org-element-at-point)) (outside-position (and (<= (line-beginning-position) (org-element-property :post-affiliated element)) (point-marker))) (org-src-window-setup (quote switch-invisibly))) (if (and (org-babel-where-is-src-block-head element) (org-edit-src-code)) (progn (unwind-protect (progn (call-interactively (function indent-for-tab-command))) (org-edit-src-exit) (if outside-position (progn (goto-char outside-position)))) t)))
  (cond ((not (and (and (boundp (quote evil-local-mode)) evil-local-mode) (evil-insert-state-p))) nil) ((org-at-item-p) (if (eq this-command (quote org-shifttab)) (org-outdent-item-tree) (org-indent-item-tree)) t) ((org-at-heading-p) (condition-case nil (progn (if (eq this-command (quote org-shifttab)) (org-promote) (org-demote))) (error nil)) t) ((org-in-src-block-p t) (let* ((element (org-element-at-point)) (outside-position (and (<= (line-beginning-position) (org-element-property :post-affiliated element)) (point-marker))) (org-src-window-setup (quote switch-invisibly))) (if (and (org-babel-where-is-src-block-head element) (org-edit-src-code)) (progn (unwind-protect (progn (call-interactively ...)) (org-edit-src-exit) (if outside-position (progn ...))) t))) t) ((and (save-excursion (skip-chars-backward " \011") (bolp)) (org-in-subtree-not-table-p)) (call-interactively (function tab-to-tab-stop)) t))
  +org-indent-maybe-h()
  run-hook-with-args-until-success(+org-indent-maybe-h)
  org-cycle(nil)
  funcall-interactively(org-cycle nil)
  call-interactively(org-cycle nil nil)
  command-execute(org-cycle)
```
After manually using tramp once this problem is solved.
(as the file where the function already  requires tramp I am a bit puzzled why this happens)

### PR DESCRIPTION
**Pull request by johnbcoughlin**
Fixes #261

### CODE REVIEW

**Comment by link0ff** [comment]
But this will load the whole TRAMP package even when the user has no intention to use commands that require TRAMP functions. A nicer thing would be to ask TRAMP developers to add an `###autoload` tag to the function `tramp-tramp-file-p`. But it would take much time until a new TRAMP version will be released. So maybe a better thing to do now would be to add something like this instead of `(require 'tramp)` in `ob-jupyter.el`:

```emacs-lisp
(autoload 'tramp-tramp-file-p "tramp" "Return t if NAME is a string with Tramp file name syntax." nil nil)
```

**Comment by johnbcoughlin** [comment]
Thank you, that's a good point. Updated to use your suggestion.

**Comment by nnicandro** [comment]
Shouldn't we have the autoload somewhere closer to `jupyter-tramp-file-name-p`? For example somewhere in `jupyter-tramp.el`. Why does it need to be in `ob-jupyter.el`? The problem doesn't really have anything to do with Org.

**Comment by nnicandro** [comment]
Closing due to inactivity.

If this issue still persists let me know.

**Pull request closed without merging**
